In [1]:
import numpy as np

d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


### Create Matrix

In [2]:
a = np.mat('5 6; 7 8')
print(a)
print()

b = np.mat([[5,6], [7,8]])
print(b)
print(type(a), type(b))
print()

mat1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

mat2 = np.matrix('1 2 3; 4 5 6; 7 8 9')

print("Matrix created using list:")
print(mat1)

print("\nMatrix created using string:")
print(mat2)

print(type(mat1), type(mat2))
print()

n1 = np.array([[5, 6], [7, 8]])
print(type(n1))


[[5 6]
 [7 8]]

[[5 6]
 [7 8]]
<class 'numpy.matrix'> <class 'numpy.matrix'>

Matrix created using list:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix created using string:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'> <class 'numpy.matrix'>

<class 'numpy.ndarray'>


In [14]:
d1 = np.mat(np.zeros((3,3)))
print("Create a 3*3 matrix of zeros:")
print(d1)
print()

d2 = np.mat(np.ones((2,4)))
print("Create a 2*4 matrix of one:")
print(d2)
print()

d3 = np.mat(np.random.rand(3,3))
print("Create a 3*3 matrix of random number between 0 and 1:")
print(d3)
print()

d4 = np.mat(np.random.randint(1, 8, size=(3,5)))
print("Create a 3*5 matrix of random number between 1 and 8:")
print(d4)
print()

d5 = np.mat(np.eye(5,5), dtype=int)
print("Create a 5*5 identity matrix:")
print(d5)

Create a 3*3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Create a 2*4 matrix of one:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Create a 3*3 matrix of random number between 0 and 1:
[[0.52518213 0.50765502 0.84061858]
 [0.14209202 0.70347357 0.51037485]
 [0.51758912 0.29190738 0.39220022]]

Create a 3*5 matrix of random number between 1 and 8:
[[1 5 2 5 3]
 [5 7 1 5 6]
 [4 7 7 6 1]]

Create a 5*5 identity matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### Matrix addition, subtraction, multiplication and division