In [1]:
import numpy as np

d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


### Create Matrix

In [2]:
a = np.mat('5 6; 7 8')
print(a)
print()

b = np.mat([[5,6], [7,8]])
print(b)
print(type(a), type(b))
print()

mat1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

mat2 = np.matrix('1 2 3; 4 5 6; 7 8 9')

print("Matrix created using list:")
print(mat1)

print("\nMatrix created using string:")
print(mat2)

print(type(mat1), type(mat2))
print()

n1 = np.array([[5, 6], [7, 8]])
print(type(n1))


[[5 6]
 [7 8]]

[[5 6]
 [7 8]]
<class 'numpy.matrix'> <class 'numpy.matrix'>

Matrix created using list:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix created using string:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'> <class 'numpy.matrix'>

<class 'numpy.ndarray'>


In [18]:
d1 = np.mat(np.zeros((3,3)))
print("Create a 3*3 matrix of zeros:")
print(d1)
print()

d2 = np.mat(np.ones((2,4)))
print("Create a 2*4 matrix of one:")
print(d2)
print()

d3 = np.mat(np.random.rand(3,3))
print("Create a 3*3 matrix of random number between 0 and 1:")
print(d3)
print()

d4 = np.mat(np.random.randint(1, 8, size=(3,5)))
print("Create a 3*5 matrix of random number between 1 and 8:")
print(d4)
print()

d5 = np.mat(np.eye(5,5), dtype=int)
print("Create a 5*5 diagonal matrix:")
print(d5)
print()

a=[1, 2, 3, 4, 5]
d6 = np.mat(np.diag(a))
print("Create a diagonal matrix from a list:")
print(d6) 

Create a 3*3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Create a 2*4 matrix of one:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Create a 3*3 matrix of random number between 0 and 1:
[[6.19568384e-01 9.30993848e-01 7.87842055e-01]
 [5.61222254e-01 1.67506034e-01 2.03087826e-01]
 [1.42668075e-04 6.32980038e-01 2.23593494e-01]]

Create a 3*5 matrix of random number between 1 and 8:
[[6 5 3 3 3]
 [7 4 5 2 2]
 [5 2 7 1 3]]

Create a 5*5 diagonal matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Create a diagonal matrix from a list:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Matrix addition, subtraction, multiplication and division

In [39]:
data1 = np.mat([[1,2], [3,4] ,[5,6]])
print(data1)

data2 = np.mat([1,2])
print(data2)

# Add
print('Result of addition: \n', data1 + data2)

# Substraction
print('Result of substraction: \n', data1 - data2)

# Division
print('Result of division: \n', data1 / data2)

# Multiplication: 左边的矩阵的列和右边矩阵的行数要一致
data3 = np.mat([[5, 6, 7], [7, 8, 9], [9, 10, 11]])
data1 =data1.T

print('Result of multiplication: \n', data1 * data3)
print('Result of multiplication: \n', data1 @ data3)
print('Result of multiplication: \n', np.dot(data1, data3))


[[1 2]
 [3 4]
 [5 6]]
[[1 2]]
Result of addition: 
 [[2 4]
 [4 6]
 [6 8]]
Result of substraction: 
 [[0 0]
 [2 2]
 [4 4]]
Result of division: 
 [[1. 1.]
 [3. 2.]
 [5. 3.]]
Result of multiplication: 
 [[ 71  80  89]
 [ 92 104 116]]
Result of multiplication: 
 [[ 71  80  89]
 [ 92 104 116]]
Result of multiplication: 
 [[ 71  80  89]
 [ 92 104 116]]


In [44]:
# 矩阵的点积与矩阵元素之间的相乘运算
n1 = np.mat('1 3 3; 4 5 6; 7 12 9')
n2 = np.mat('2 6 6; 8 10 12; 14 24 18')

print(n1)
print(n2)

print('矩阵相乘的结果: \n', n1 * n2)    # 点积
print('矩阵相乘的结果: \n', np.matmul(n1, n2))    # 点积


print('矩阵对应元素相乘: \n', np.multiply(n1, n2))    # 矩阵元素相乘



[[ 1  3  3]
 [ 4  5  6]
 [ 7 12  9]]
[[ 2  6  6]
 [ 8 10 12]
 [14 24 18]]
矩阵相乘的结果: 
 [[ 68 108  96]
 [132 218 192]
 [236 378 348]]
矩阵相乘的结果: 
 [[ 68 108  96]
 [132 218 192]
 [236 378 348]]
矩阵对应元素相乘: 
 [[  2  18  18]
 [ 32  50  72]
 [ 98 288 162]]


### Transpose of matrix and inversion of matrix

In [51]:
n1 = np.mat('1 3 1; 4 5 5; 7 12 9')
print(n1)
print()
print('After Transposing: \n', n1.T)
print()
print('Inversion of matric: \n', n1.I)

A = np.linalg.inv(n1)
print('\nInverse Matrix: \n', A)

[[ 1  3  1]
 [ 4  5  5]
 [ 7 12  9]]

After Transposing: 
 [[ 1  4  7]
 [ 3  5 12]
 [ 1  5  9]]

Inversion of matric: 
 [[ 3.   3.  -2. ]
 [ 0.2 -0.4  0.2]
 [-2.6 -1.8  1.4]]

Inverse Matrix: 
 [[ 3.   3.  -2. ]
 [ 0.2 -0.4  0.2]
 [-2.6 -1.8  1.4]]
