In [1]:
import numpy as np

n1 = np.array([1,2,3])      # 创建一维数组
print(n1)

d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


[1 2 3]


In [2]:
# 创建一个带小数点的数组
import numpy as np
n2 = np.array([0.1, 0.2, 0.3])
print(n2)

[0.1 0.2 0.3]


In [3]:
# 创建一个二维数组
n3 = np.array([[1,2], [3, 4]])
print(n3)

[[1 2]
 [3 4]]


In [4]:
range_arr = np.arange(0, 10, 2)  # 创建一个步长为2的数组，范围是[0, 10)
print(range_arr)

[0 2 4 6 8]


In [5]:
linspace_arr = np.linspace(0, 1, 5)  # 创建包含5个元素的数组，均匀分布在[0, 1]之间
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [6]:
random_arr = np.random.rand(2, 3)  # 创建一个2x3的随机数组，元素在[0, 1)范围内
print(random_arr)

[[0.90587043 0.56332411 0.29472438]
 [0.05360614 0.43178159 0.7144524 ]]


In [7]:
# 创建数组时指定数据类型
lst = [1, 2, 3]
n4 = np.array(lst, dtype=float)
print(n4)
print(n4.dtype)
print(type(n4))
print(type(n4[0]))

[1. 2. 3.]
float64
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [8]:
# 数组复制
import numpy as np

# 默认情况（copy=True）
original_array = np.array([1, 2, 3])
copied_array = np.array(original_array)

# 修改副本数组，不影响原始数组
copied_array[0] = 100

print(original_array)  # 输出: [1 2 3]
print(copied_array)    # 输出: [100 2 3]



[1 2 3]
[100   2   3]


In [9]:
# 指定维数
import numpy as np
lst = [1, 2, 3]
n7 = np.array(lst, ndmin=3) # ndmin 用于设置数组的维度
print(n7)

[[[1 2 3]]]


In [10]:
# 不同方式创建数组

n8 = np.empty([4, 3], dtype=int)  # [4,3] 表示4行3列
print(n8)

[[  -66084437  1072495843  1226551151]
 [ 1071777472 -1597589752  1070783683]
 [ 2044308000  1068200515  1125287856]
 [ 1071358543  1198238647  1072094411]]


In [11]:
zeros_arr = np.zeros((3, 4))  # 创建一个全零的3x4数组
ones_arr = np.ones((2, 3))    # 创建一个全一的2x3数组
identity_matrix = np.eye(3)  # 创建一个3x3的单位矩阵

print('zeros_arr\n', zeros_arr)     # 输出结果: 默认浮点型
print('ones_arr\n', ones_arr)
print('identity_matrix\n', identity_matrix)

zeros_arr
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones_arr
 [[1. 1. 1.]
 [1. 1. 1.]]
identity_matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# numpy.full(shape, fill_value, dtype=None, order='C')
# 函数用于创建一个指定形状和数据类型的数组，并用指定的常数值填充该数组的所有元素。
import numpy as np
n11 = np.full(3, 8)  # 创建一个一维数组，元素都是8
print(n11)

n12 = np.full((3, 4), 8)  # 创建一个二维数组，3行4列， 元素都是8
print(n12)

[8 8 8]
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
