`np.asarray()` 函数是 NumPy 中用于将输入转换为数组的函数。其语法如下：

```python
numpy.asarray(a, dtype=None, order=None)
```

参数说明：
- **`a`：** 输入数据，可以是列表、元组、数组等。
- **`dtype`：** 数组的数据类型，可选参数。如果未提供，将根据输入数据类型推断。
- **`order`：** 数组元素的存储顺序，可选参数。可以是 'C'（按行存储）或 'F'（按列存储）。

`np.asarray()` 将输入转换为数组，如果输入已经是数组，则不进行拷贝，如果输入是其他可迭代对象，将其转换为数组。这使得 `np.asarray()` 是一个方便的方法，可以确保输入被视为数组。

In [8]:
import numpy as np

# 通过列表创建数组
n1 = np.asarray([1, 2, 3])
print(n1)
print(type(n1))

print('*'*10)
# 通过列表的元组创建数组
n2 = np.asarray([(1, 2, 3), (4, 5, 6)])
print(n2)
print(type(n2))

print('*'*10)
# 通过元组创建数组
n3 = np.asarray((1, 2, 3))
print(n3)
print(type(n3))

print('*'*10)
# 通过元组的元组创建数组
n4 = np.asarray(((1, 2, 3), (4, 5, 6)))
print(n4)
print(type(n4))

print('*'*10)
# 通过元组的列表创建数组
n5 = np.asarray(([1, 2], [4, 5]))
print(n5)

[1 2 3]
<class 'numpy.ndarray'>
**********
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
**********
[1 2 3]
<class 'numpy.ndarray'>
**********
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
**********
[[1 2 3]
 [4 5 6]]


`numpy.frombuffer()` 函数用于将一个缓冲区（通常是字节对象）转换为一个 NumPy 数组。其语法如下：

```python
numpy.frombuffer(buffer, dtype=float, count=-1, offset=0)
```

参数说明：
- **`buffer`：** 缓冲区对象，通常是一个字节对象（`bytes`）。
- **`dtype`：** 数组的数据类型，可选参数。默认为 `float`。
- **`count`：** 要读取的元素数量，可选参数。默认为 -1，表示读取整个缓冲区。
- **`offset`：** 起始读取位置的偏移量，可选参数。默认为 0。

In [12]:
# 动态数组
import numpy as np

# 从字节对象创建数组
byte_data = b'Yolanda'
arr1 = np.frombuffer(byte_data, dtype='S1')  # 'S1' 表示每个元素是一个字节的字符串
print(arr1)

# 从字节数组中的部分元素创建数组
arr2 = np.frombuffer(byte_data, dtype='S1', count=4)
print(arr2)

# 使用偏移量创建数组
arr3 = np.frombuffer(byte_data, dtype='S1', offset=2)
print(arr3)


[b'Y' b'o' b'l' b'a' b'n' b'd' b'a']
[b'Y' b'o' b'l' b'a']
[b'l' b'a' b'n' b'd' b'a']


`numpy.fromiter()` 函数用于从可迭代对象创建一个一维数组。其语法如下：

```python
numpy.fromiter(iterable, dtype, count=-1)
```

参数说明：
- **`iterable`：** 可迭代对象，提供数据的来源。
- **`dtype`：** 数组的数据类型。
- **`count`：** 要从可迭代对象中读取的元素数量，可选参数。默认为 -1，表示读取所有元素。

In [16]:
import numpy as np

# 从生成器表达式创建数组
iterable_data = (x*x for x in range(5))
print(iterable_data)
for x in iterable_data:
    print(x, end=' ')
    
arr1 = np.fromiter(iterable_data, dtype=int)
print(arr1)

# 从列表中创建数组
arr2 = np.fromiter([1, 2, 3, 4, 5], dtype=float)
print(arr2)

# 从元组中读取部分元素创建数组
arr3 = np.fromiter((x for x in range(10)), dtype=int, count=5)
print(arr3)


<generator object <genexpr> at 0x000001E17A22F970>
0 1 4 9 16 []
[1. 2. 3. 4. 5.]
[0 1 2 3 4]


`numpy.empty_like()` 函数用于创建一个与给定数组具有相同形状（shape）和数据类型（dtype）的未初始化数组。它返回一个新的数组，该数组的元素值取决于内存状态。

其语法如下：

```python
numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None)
```

参数说明：
- **`prototype`：** 用作形状和数据类型参考的数组。
- **`dtype`：** 所需的输出数据类型，可选参数。如果未提供，则使用 `prototype` 的数据类型。
- **`order`：** 数组元素的存储顺序，可选参数。默认为 'K'。
- **`subok`：** 如果为 `True`，则返回一个与 `prototype` 相同的子类，否则返回基类。
- **`shape`：** 输出数组的形状，可选参数。如果未提供，则使用 `prototype` 的形状。

In [17]:
import numpy as np

# 创建一个形状为 (2, 3)、数据类型为 int 的数组
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 使用 empty_like 创建一个与 arr 具有相同形状和数据类型的未初始化数组
empty_arr = np.empty_like(arr)

print(empty_arr)



[[1238553856        481          0]
 [         0     131074          0]]


`numpy.zeros_like()` 函数用于创建一个与给定数组具有相同形状（shape）和数据类型（dtype）的数组，但所有元素的值都设置为零。

```python
numpy.zeros_like(prototype, dtype=None, order='K', subok=True, shape=None)
```

参数说明：
- **`prototype`：** 用作形状和数据类型参考的数组。
- **`dtype`：** 可选参数，新数组的数据类型。如果未提供，将使用 `prototype` 的数据类型。
- **`order`：** 数组元素的存储顺序，可选参数。默认为 'K'（保留输入数组的顺序）。
- **`subok`：** 如果为 True，则子类将被传递；否则，返回标准的数组。默认为 True。
- **`shape`：** 可选参数，如果指定，则返回具有指定形状的数组。默认为 None，即返回与 `prototype` 相同形状的数组。

`zeros_like` 主要用于创建一个与现有数组具有相同形状的数组，但所有元素的值都初始化为零。这在需要一个占位符数组，并希望初始化所有元素为零的情况下很有用。


In [18]:
import numpy as np

# 创建一个原始数组
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

# 使用 zeros_like 创建具有相同形状的数组，但所有元素值都为零
arr2 = np.zeros_like(arr1)

print("Original Array:")
print(arr1)

print("\nZeros-like Array:")
print(arr2)


Original Array:
[[1 2 3]
 [4 5 6]]

Zeros-like Array:
[[0 0 0]
 [0 0 0]]


`numpy.ones_like()` 函数用于创建一个与给定数组具有相同形状（shape）和数据类型（dtype）的数组，但所有元素的值都被初始化为1。

```python
numpy.ones_like(prototype, dtype=None, order='K', subok=True, shape=None)
```

参数说明：
- **`prototype`：** 用作形状和数据类型参考的数组。
- **`dtype`：** 可选参数，新数组的数据类型。如果未提供，将使用 `prototype` 的数据类型。
- **`order`：** 数组元素的存储顺序，可选参数。默认为 'K'（保留输入数组的顺序）。
- **`subok`：** 如果为 True，则子类将被传递；否则，返回标准的数组。默认为 True。
- **`shape`：** 可选参数，如果指定，则返回具有指定形状的数组。默认为 None，即返回与 `prototype` 相同形状的数组。

`ones_like` 主要用于创建一个与现有数组具有相同形状的数组，但是其所有元素的值都被初始化为1。这在需要一个占位符数组，并希望初始化所有元素为1的情况下很有用。


In [19]:
import numpy as np

# 创建一个原始数组
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

# 使用 ones_like 创建具有相同形状的数组，但所有元素值都为1
arr2 = np.ones_like(arr1)

print("Original Array:")
print(arr1)

print("\nOnes-like Array:")
print(arr2)


Original Array:
[[1 2 3]
 [4 5 6]]

Ones-like Array:
[[1 1 1]
 [1 1 1]]


`numpy.full_like()` 函数用于创建一个与给定数组具有相同形状（shape）和数据类型（dtype）的数组，但所有元素的值都被初始化为指定的常数值。

```python
numpy.full_like(prototype, fill_value, dtype=None, order='K', subok=True, shape=None)
```

参数说明：
- **`prototype`：** 用作形状和数据类型参考的数组。
- **`fill_value`：** 新数组中所有元素的初始值。
- **`dtype`：** 可选参数，新数组的数据类型。如果未提供，将使用 `prototype` 的数据类型。
- **`order`：** 数组元素的存储顺序，可选参数。默认为 'K'（保留输入数组的顺序）。
- **`subok`：** 如果为 True，则子类将被传递；否则，返回标准的数组。默认为 True。
- **`shape`：** 可选参数，如果指定，则返回具有指定形状的数组。默认为 None，即返回与 `prototype` 相同形状的数组。

`full_like` 主要用于创建一个与现有数组具有相同形状的数组，但是其所有元素的值都被初始化为指定的常数值。这在需要一个占位符数组，并希望初始化所有元素为特定值的情况下很有用。


In [20]:
import numpy as np

# 创建一个原始数组
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

# 使用 full_like 创建具有相同形状的数组，所有元素值都为指定的常数值
arr2 = np.full_like(arr1, fill_value=10)

print("Original Array:")
print(arr1)

print("\nFull-like Array:")
print(arr2)


Original Array:
[[1 2 3]
 [4 5 6]]

Full-like Array:
[[10 10 10]
 [10 10 10]]
