In [1]:
import numpy as np

d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
# index: start with 0
# 1D array
a1 = np.array([1,2,3,4,5])

print(a1[0])
print(a1[-2])

# 2D array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)
print(a2[1][1])
print(a2[1,1])
print(a2[1])
print(a2[-1])

1
4
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
7
[ 6  7  8  9 10]
[ 6  7  8  9 10]


In [3]:
# Slice   1D array
a3 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(a3[:3])  # If the starting position is omitted, it defaults to 0. Including head but not tail[0,3), default step: 1
print(a3[3: 6])
print(a3[6:])  # If the ending position is omitted, it defaults to the length of the array. Including tail but not head[6,10)
print(a3[::2])  # step: 2
print(a3[1::5])  # step: 5
print(a3[::])   # Get all elements in the array

print(a3[::-1])  # reverse
print(a3[-1:-9:-3])
print(a3[-5:-8:-2])

[10 20 30]
[40 50 60]
[ 70  80  90 100]
[10 30 50 70 90]
[20 70]
[ 10  20  30  40  50  60  70  80  90 100]
[100  90  80  70  60  50  40  30  20  10]
[100  70  40]
[60 40]


In [4]:
# The difference between list slicing and array slicing

# list slicing
list1 = [1, 2, 3, 4, 5]
list_slice = list1[1:4]
print("List Slice:", list_slice)

# Modify the sliced list
list_slice[1] = 101
print("Original List:", list1)
print("Modified List:", list_slice)

print()

# NumPy array slicing
array1 = np.array([1, 2, 3, 4, 5])
array_slice = array1[1:4]
print("Array Slice:", array_slice)

# Modify the array after slicing
array_slice[1] = 101
print("Original Array:", array1)
print("Modified Array:", array_slice)



List Slice: [2, 3, 4]
Original List: [1, 2, 3, 4, 5]
Modified List: [2, 101, 4]

Array Slice: [2 3 4]
Original Array: [  1   2 101   4   5]
Modified Array: [  2 101   4]


In [5]:
# 2D array slice

arr1 = np.array([[1,2,3,4],[5,6,7,8], [9, 10,11,12]])
print(f'Original: \n{arr1}\n')

print(f'Row 1, Column 2: {arr1[1,2]}\n')  
print(f'Row 0-2 (Exnclude 2), Column 1 to the end: \n{arr1[:2, 1:]}\n')
print(f'The line before the comma indicates the row with index 1 and ends with the column with index 2, excluding 2: {arr1[1,:2]}\n')
print(f'Start Row 0, end Row 2, and Column 2: {arr1[:2,2]}\n')
print(f'Select the first element of all rows: \n{arr1[:,:1]}\n')



Original: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Row 1, Column 2: 7

Row 0-2 (Exnclude 2), Column 1 to the end: 
[[2 3 4]
 [6 7 8]]

The line before the comma indicates the row with index 1 and ends with the column with index 2, excluding 2: [5 6]

Start Row 0, end Row 2, and Column 2: [3 7]

Select the first element of all rows: 
[[1]
 [5]
 [9]]

