### Reshape

In [1]:
import numpy as np

d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
n = np.arange(6)
print(n)

n1 = n.reshape(2,3)
print(n1)

print('*'*20)

n = np.array([[1,2,3],[4,5,6]])
n2 = n.reshape(3,2)
print(n2)


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
********************
[[1 2]
 [3 4]
 [5 6]]


### Transpose

Transpose is the operation of exchanging the rows and columns of a matrix / array

In [8]:
n = np.arange(24).reshape(4,6)

# 使用 transpose() 函数进行转置
transposed_array_1 = np.transpose(n)

# 使用数组的 .T 属性进行转置
transposed_array_2 = n.T

print("Original Array:")
print(n)

print("\nTransposed Array (using transpose()):")
print(transposed_array_1)

print("\nTransposed Array (using .T):")
print(transposed_array_2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Original Array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Transposed Array (using transpose()):
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]

Transposed Array (using .T):
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
