In [1]:
import numpy as np

d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
d:\Learning-Material\pythonPractice\venv\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


### Add Element

In [2]:
arr = np.array([1, 2, 3])

# 在数组末尾添加元素
arr_append = np.append(arr, 4)

# 在指定位置插入元素
arr_insert = np.insert(arr, 1, 5)

print("Original Array:")
print(arr)

print("\nArray after Append:")
print(arr_append)

print("\nArray after Insert:")
print(arr_insert)


Original Array:
[1 2 3]

Array after Append:
[1 2 3 4]

Array after Insert:
[1 5 2 3]


In [16]:
n1 = np.array([[1,2], [3,4], [5,6]])
n2 = np.array([[10,20], [30,40], [50,60]])

print('Original array: ')
print(n1)
print(n2)
print()

print('Add data horizontally: ')
print(np.hstack((n1, n2)))

print()

print('Add data vertically: ')
print(np.vstack((n1, n2)))

Original array: 
[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]
 [50 60]]

Add data horizontally: 
[[ 1  2 10 20]
 [ 3  4 30 40]
 [ 5  6 50 60]]

Add data vertically: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10 20]
 [30 40]
 [50 60]]


### Delete Element

<strong>axis: 0 means Row, 1 means Column</Strong   >

In [13]:
n1 = np.array([[1,2], [3,4], [5,6]])
print(n1)
print()

# Delete Row 3 
n2 = np.delete(n1, 2, axis=0)
print('After Delete Row 3: \n', n2)
print()

# Delete Column 2
n3 = np.delete(n1, 1, axis=1)
print('After Delete Column 2: \n', n3)
print()

# Delete Row 2 and Row 3
n4 = np.delete(n1, [1,2], axis=0)
print('After Delete Row 2 and Row 3: \n',n4)
print()

# axis: 0 means Row, 1 means Column

[[1 2]
 [3 4]
 [5 6]]

After Delete Row 3: 
 [[1 2]
 [3 4]]

After Delete Column 2: 
 [[1]
 [3]
 [5]]

After Delete Row 2 and Row 3: 
 [[1 2]]



### Modify

In [20]:
import numpy as np

arr = np.array([[1,2], [3,4], [5,6]])
print("Array before Modification: ")
print(arr)

# Modifying the element at Row 3, Column 2 to 10
arr[2][1] = 10

print("Array after Modification: ")
print(arr)


Array before Modification: 
[[1 2]
 [3 4]
 [5 6]]
Array after Modification: 
[[ 1  2]
 [ 3  4]
 [ 5 10]]


### Search

`numpy.where()` 函数是 NumPy 中用于根据指定的条件返回数组中满足条件元素的索引的函数。该函数的基本语法如下：

```python
numpy.where(condition[, x, y])
```

- `condition`: 表示条件，是一个布尔数组或者可以被转换为布尔数组的表达式。
- `x`, `y`（可选）: 是两个数组，表示满足条件和不满足条件时的替代值。如果未提供，则返回满足条件元素的索引。

In [28]:
n = np.arange(10, 21)
print(n)

# Find the element index large than 15
index = np.where(n > 15)
# Find the element index large than 15
element = n[np.where(n > 15)]

print("\nIndices where element > 5:")
print(index)

print()

print("Element where element > 5:")
print(element)


n3 = np.where(n>15, 2, 0)  # If the elements in the array are greater than 5, output 2, otherwise output 0
print(n3)

[10 11 12 13 14 15 16 17 18 19 20]

Indices where element > 5:
(array([ 6,  7,  8,  9, 10], dtype=int64),)

Element where element > 5:
[16 17 18 19 20]
[0 0 0 0 0 0 2 2 2 2 2]
